Bumping application version to v1.95.1 and bumping pgvecto-rs
immich-app/immich-charts pull request #67
Opened 2024-02-24 16:00 UTC by samholton

Also added example comments for mounting a read-only external library from NFS

2024-02-24 16:29 UTC, prometheanfire commented
I suppose the migration plan we should do is to manually kill containers when upgrading (kinda expected, just asking)

2024-02-24 16:49 UTC, samholton commented
> I suppose the migration plan we should do is to manually kill containers when upgrading (kinda expected, just asking)

Yeah, I upgraded from ` v1.94.1` and just needed to restart the postgres pod once after it upgraded

2024-02-27 05:03 UTC, mertalev reviewed
The version bump looks good, but I'll defer to @bo0tzz on the external library example

2024-02-27 09:23 UTC, djjudas21 commented on charts/immich/values.yaml
> +  #     path: /mnt/to/photos
Not technically related to the PR, but as it's just the addition of a comment it's probably not worth splitting it out

2024-02-27 09:40 UTC, bo0tzz commented on charts/immich/values.yaml
> +  #     path: /mnt/to/photos
This is unrelated to the PR, we don't need to document options that are already properly documented by common-library, and finally the version of the lib that we use does not support `type: nfs` ;)

2024-02-27 09:40 UTC, bo0tzz requested changes
Please remove the unrelated changes

2024-02-27 13:01 UTC, samholton commented on charts/immich/values.yaml
> +  #     path: /mnt/to/photos
> the version of the lib that we use does not support `type: nfs`

Interesting, when I was first trying to spin up immich to test, I wanted to use a readonly external library to ensure it didn't change any files on TrueNAS Scale. As someone new to Immich, it was not quick/easy to do this. However, the above did work to access the files, so perhaps the common library is missing documentation or its not easy to find.

It was also not immediately apparent that both containers required access to the files. Not hard to debug, but also not easy and user friendly as a new user.

2024-02-27 13:41 UTC, bo0tzz approved these changes

2024-02-27 13:42 UTC, merged